version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"


  juiceShop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"

  jenkins:
    #image: jenkins/jenkins
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    links:
      - hub:hub.com
      - juiceShop:juiceShop.com

    # uncomment for docker in docker
    privileged: true